### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by oo8dev** [DiD3n/pb2e#1]
> cmake CMakeLists.txt 
-- The C compiler identification is GNU 8.2.1
-- The CXX compiler identification is GNU 8.2.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:11 (file):
  file STRINGS file "/home/XXX/Desktop/pb2e/BuildCounter.txt" cannot
  be read.

-- Configuring incomplete, errors occurred!
See also "/home/XXX/Desktop/pb2e/CMakeFiles/CMakeOutput.log".

**Comment by DiD3n** [comment]
Cmake is frequently updated. In the next version that bug will be fixed. 
Restart of cmake should fix this. 🙂
